### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by clumsyzombie** [J0hnHawk/FS19_Webstats#1]
I am interested in this project you have going on here. I have been working on making my own and had it in FS17 it was nothing like this. I have tried to get this to work with a ftp I have but noticed I am not sure it supports passive ftp. I have done this and in FileZilla Server I setup a user farm and set the users home to C:\Users\Administrator\Documents\My Games\FarmingSimulator2019
in the folder I have savegame1
So what I have done is I hit my website and clicks on ##HEAD_FTP## I then placed in 
IP address
Port 3333
Path /savegame1/
user: farm
password: *****
Map left alone 
WebStats Password  Never setone so I just made one up

Unable to connect to my ftp 
Error! ##ERROR_FTPSERVER##

I would assume it is the fact about passive FTP. It seems like filezilla server like passive only. Was wanting to see what your thoughts are on this.

**Comment by clumsyzombie** [comment]
Honestly most places since they are behind a firewall force passive ftp so in the php code you need to include passive ftp 
http://php.net/manual/en/function.ftp-pasv.php

That is why G-Portal is having issues with this as a note in your code in the install.php

**Comment by J0hnHawk** [comment]
I tested many ways to get ftp run with our g-portal server. None worked only the workaround I currently build in which i found in g-portal forum. 
But FTP is only a soulution I want to use until hopefully the giants web api is extended. FTP is slowlier (at least in the current version I've build in) and the minimal autosavetimer is 5 minutes - to slow in my opinion for a website which should show actual data. :-/

I'm not sure but in first commits you can find some trys to get the data with php ftp functions from the server.

**Comment by clumsyzombie** [comment]
> I tested many ways to get ftp run with our g-portal server. None worked only the workaround I currently build in which i found in g-portal forum.
> But FTP is only a soulution I want to use until hopefully the giants web api is extended. FTP is slowlier (at least in the current version I've build in) and the minimal autosavetimer is 5 minutes - to slow in my opinion for a website which should show actual data. :-/
> 
> I'm not sure but in first commits you can find some trys to get the data with php ftp functions from the server.

Any way you know of to enable passive I am not a good PHP programmer I can hack stuff together but thats about all I didn't see where it could be placed in the code.

**Comment by clumsyzombie** [comment]
> I tested many ways to get ftp run with our g-portal server. None worked only the workaround I currently build in which i found in g-portal forum.
> But FTP is only a soulution I want to use until hopefully the giants web api is extended. FTP is slowlier (at least in the current version I've build in) and the minimal autosavetimer is 5 minutes - to slow in my opinion for a website which should show actual data. :-/
> 
> I'm not sure but in first commits you can find some trys to get the data with php ftp functions from the server.

This is one I built a long long time ago for FS17 but I like yours better
http://gameonline365.com/farm/index.html

But this is using the SDK they provided. So what I have found is that since my FS is behind a firewall I have had issues with having passive FTP on. So that is why I was wondering if you had away to add passiv ftp. I can try to not use passiv ftp but i have had a number of issues that is why I am asking not sure if that is anything that can be added.

**Comment by J0hnHawk** [comment]
Let's wait until the next patch of Giants. Maybe it will extend the Web API and we don't need to use FTP at all. 

Until then I'm working on the core of my web stats - the parsing and processing of the XML files of the savegames.

**Comment by J0hnHawk** [comment]
Take a look to this #2 
Unlike what I wrote 2 days ago, I have now extended the FTP support.

**Comment by clumsyzombie** [comment]
So here is my issue I have a hosted server at home with ftp to it. 
I am able to ftp just fine with the folder you can see file 1 that shows the FTP. 
So then I go over to web software and place in my testing info in number 2 and I get an error of Error! ##ERROR_FTPSERVER##
![1](https://user-images.githubusercontent.com/15150210/50877824-50eacd00-1399-11e9-9190-8be6745983e3.PNG)
![2](https://user-images.githubusercontent.com/15150210/50877829-534d2700-1399-11e9-9b17-b2bfe88336a8.PNG)

So I started to think about passiv FTP and if you have it in your code that is why I pointed to that. I just tried it again and I am not able to get it to connect for some reason when using ftp program everything works perfect you can see that in the first screen shot. 

Also to be honest I don't even see an attempt to connect in my ftp logs at all. So that is why I was wondering if you planed on adding or writing passiv ftp into the code.

**Comment by J0hnHawk** [comment]
According to the error message, the PHP script cannot connect to the FTP server. So you can't find any entries in the log file of the FTP server ;-)

I just created an FTP server on my NAS and I was able to transfer data via FTP (with SSL and without) with my script. 

Is there perhaps a firewall through which your web server cannot connect to the FTP server? It can't be due to the passive FTP, because the connection itself is not established.

**Comment by clumsyzombie** [comment]
Maybe my web host is blocking it I am running it on port 3333 so try to get around it if the problem are on my farming sim server I wouldn't be able to see it with a ftp client. WOW I am with you on this it is kind of a pain in the butt when Giant dose not have everything ready to go at launch. Let me toy with my web host to my game host see what happens on the port... It could be the webhost firewall. I know port 21 works because I do nightly automated backups in cpanel to my same location hosting my game server. They work with out any issues.  I might need to pick a more common port or temp disable that see if it work for a good test.

**Comment by J0hnHawk** [comment]
Could we close this topic? In tests on my and another FTP server (#2) FTP access is working. Whats up with your server?

**Comment by clumsyzombie** [comment]
I am not able to do any more work on it right now sorry I have had to move on so we can close for now
