### ISSUE TITLE
Hallo

### ISSUE THREAD

**Issue by Alki-Agrar** [J0hnHawk/FS19_Webstats#2]
Hi, ich hoffe ich nerve dich nicht damit, aber könntest du mir evtl sagen ob es im momentanem Stadium normal ist dass nach den Einstellungen wenn ich auf Zur Übersicht klicke nichts mehr kommt? Oder habe ich da einen Fehler gemacht? 
Ich habe die Daten über FTP eingebunden...

LG Chris von Alki-Agrar

**Comment by J0hnHawk** [comment]
Mh, eigentlich nicht ;-)
Vielleicht hast du das gleiche Problem wie clumsyzombie (#1). Ich benutze im Moment nicht wirklich "richtige" FTP Funktionen um die Daten von unserem G-Portal Server abzuholen. Anders komme ich nicht an die Daten ran. Bei welchem Anbieter bist du denn?
Wie ich aber auch schon clumsyzombie schrieb, hoffe ich eigenltich, FTP gar nicht benutzen zu müssen. Ich hab gerade heute mal wieder im Giants Forum nachgefragt, ob denn die Web API erweitert wird. (https://forum.giants-software.com/viewtopic.php?f=957&t=136246&p=1087889#p1087889)
Wenn sich mit dem nächsten Patch von Giants nichts tut, werde ich den FTP-Zugang wieder einbauen und für G-Portal dann eine extra Option basteln.

**Comment by J0hnHawk** [comment]
Ach, fällt mir noch ein: Eine leere Seite könnte auch ein Fehler in meinem Script sein. Je nach dem welchen Stand du herunter geladen hast, werden die Fehlermeldungen nicht angezeigt. Im root-Verzeichnis wird aber eine error.log Datei angelegt. Guck doch mal ob da was drin steht.

**Comment by J0hnHawk** [comment]
Ich hab ein paar Screenshots hochgeladen, wie es aussehen sollte...

**Comment by Alki-Agrar** [comment]
Hi, Danke erstmal dass du dir überhaupt Zeit nimmst dafür! Ich weiß dass es nicht selbstverständlich ist und weis das auch sehr zu schätzen!!!
Hier ist die Website: http://webstats.alki-agrar.de/

Ich bin bei gamed.de / das savegame wird dort gespeichert unter ls2019/gameProfile/savegameXX... Ich schätze dass macht Probleme?

Und das die Error Log dazu: 

[error.log](https://github.com/J0hnHawk/FS19_Webstats/files/2734515/error.log)

Die ist halt ganz schön voll :( Siehst du da eventuell einen Fehler?
 

Achso, und die Version ist das neueste was heute von dir kahm.

**Comment by J0hnHawk** [comment]
Kein Ding. Letztlich bin ich irgendwann ja sowieso auf Fehlermeldungen/Verbesserungsvorschläge angewiesen. Im Moment forciere ich dies Projekt nur noch nicht so richtig, weil die Web API nicht alle Daten liefert und der ursprüngliche Zweck - im Blick halten der Industrien - mangels Fabrikscript noch nicht wieder vorhanden ist.

Ein Großteil der Fehlermeldungen in deinem Log ist darauf zurück zu führen, dass XML Dateien leer sind. Ich denke es ist tatsächlich wie bei clumsyzombie (#1). Mein Workaround für G-Portal funktioniert nicht bei anderen Anbietern. Ich baue das Programm mal um, bzw. erweitere es.

**Comment by J0hnHawk** [comment]
So, ich habe die Funktion zum Abrufen der Daten um die FTP Funktionen von PHP erweitert.
Schau mal, ob es funktioniert. Mit unserem Server kann ich es ja leider nicht testen.

**Comment by J0hnHawk** [comment]
Hab den Installationsprozess erweitert... ;-)

**Comment by Alki-Agrar** [comment]
So siehts momentan aus... :(

![server](https://user-images.githubusercontent.com/46451443/50847940-238b2880-1373-11e9-9814-327f7bc0bcfb.PNG)

Kann ich dich mal nicht-öffentlich kontaktieren? Dann würde ich dir unsere Serverdaten geben, dann kannst es dir ma anschauen falls du möchtest.

Und hier nochma die Errorlog 
[error (2).log](https://github.com/J0hnHawk/FS19_Webstats/files/2737864/error.2.log)

**Comment by J0hnHawk** [comment]
Oups, da habe ich eine Variable bei der Nutzung von SSL für die Verbindung zum FTP Server vergessen. 
Die Variable habe ich jetzt hinzugefügt (898d10af3e9f9596031d24a7e7da3e8efca042bd).
Ich habe es gerade erfolgreich mit einem eigenen FTP Server auf meinem NAS getestet (mit und ohne SSL). 
Meine E-Mail-Adresse steht im Kopf jeder PHP Datei ;-)

**Comment by Alki-Agrar** [comment]
Hi, jetzt sagt er... Fehler! ##ERROR_FTPUSERPASS## ... Soll ich dir mal meine Zugangsdaten schicken?

**Comment by J0hnHawk** [comment]
Das kannst du machen. Ich komm' aber erst frühestens morgen Abend dazu, zu testen.
Nachdem ich Mittwoch die Variable und damit den Fehler oben berichtigt hatte, habe ich auf meinem NAS selbst einen FTP Server eingerichtet und damit einmal mit und einmal ohne SSL getestet - erfolgreich.
Die Verbindung und der Download von Nicht-G-Portal-Servern sollte also eigentlich funktionieren.

Schau doch mal, ob du die nicht tatsächlich einfach nur beim Benutzernamen oder dem Passwort vertippt hast.

**Comment by J0hnHawk** [comment]
Da auf eurem Server Web Stats inzwischen läuft, schließe ich das Thema hier mal.
