### ISSUE TITLE
Default farm permanently connected

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS19_Webstats#25]
can be set in
/index.php?page=farms&join_farm=1
permanent connection to the farm?

so that every visitor does not have to click on connect to ...
We only have one farm ...
Thanks JanSe

**Comment by J0hnHawk** [comment]
I could add an "auto-join" if only one farm exists, yes.

**Comment by ghost** [comment]
Yes, it would be great for us. thanks JanSe
