### ISSUE TITLE
Clean install, errors on all choices

### ISSUE THREAD

**Issue by Nessiroj** [J0hnHawk/FS19_Webstats#38]
Just downloaded the Master Zip, only to get errors on all install methods.

Webserver and Gameserver are on the same server (localmachine // 127.0.0.1)

Choice 
**API:** Alot off errors (Local API only not accessable by internet, doesn't matter if using in localhost // 127.0.0.1 or internal ip of the server in the install) - https://pastebin.com/nBxD6pH8

**FTP:** Does not work at all, does get stuck on the install before showing the Webstatswebsite ( doesn't matter if using in localhost // 127.0.0.1 or internal ip of the server in the install) - https://pastebin.com/1xcRJfxq

**Localsave** Does kinda work (missions/users are visable) but gives errors on prices etc - https://pastebin.com/xA8mTetp

Webstats is accessable by https://nessirojgaming.eu/fsstats/index.php - Running localmode atm.

Yes i do know there are translations missing (##token##) not referring to those ;-)

**Extra info:**
2x Xeon X5660
64GB RAM

Webserver running Win 10 x64
Apache Version:2.4.37
PHP Version:7.3.1

**Comment by aajjager** [comment]
Hi Nessiroj,

This has nothing todo with the Webstats, but rather your PHP instance.

I see you are on windows, so please do the following
1. Open your php.ini where PHP is installed. 
2. Go to the section extentions.
3. add the following line and save the php.ini : extension=php_ftp.dll
4. Open the index.php and try the FTP option again.


Let me know if there are any issues.

Thanks.,

**Comment by Nessiroj** [comment]
Cheers, this fixed the FTP install atleast, now just need to check if the information of the economy gets "imported"
