### ISSUE TITLE
Cannot delete server settings

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS19_Webstats#41]
Hello,
Now it doesn't work: Delete server settings
PHP error:
[01-Aug-2019 16:23:28 Europe/Berlin] PHP Notice:  Undefined variable: config in /data/web/include/options.php on line 53

Server saved by new url method. 
Thanks :)

**Comment by J0hnHawk** [comment]
Damn! I forgot this to change.

**Comment by J0hnHawk** [comment]
Adjusted to new config file (a0e2e569327f3c54858baf00e1b981453e73de77)
