### ISSUE TITLE
Undefined property

### ISSUE THREAD

**Issue by ralfmuehle** [J0hnHawk/FS19_Webstats#43]
Zuerst einmal vielen Dank für das super Tool. 

Ich verwende XAMPP für Windows mit PHP Version 5.6.40 (habe auch schon neuere Versionen probiert) und bekomme bei den Verkaufspreisen-Seiten und auf der Bilanz-Seite die folgenden Fehler angezeigt:

Notice: Undefined property: Savegame::$economy in E:\xampp\htdocs\FS19_Webstats\include\savegame\Prices.class.php on line 41

Notice: Trying to get property of non-object in E:\xampp\htdocs\FS19_Webstats\include\savegame\Prices.class.php on line 127

Notice: Trying to get property of non-object in E:\xampp\htdocs\FS19_Webstats\include\savegame\Prices.class.php on line 127

Warning: Invalid argument supplied for foreach() in E:\xampp\htdocs\FS19_Webstats\include\savegame\Prices.class.php on line 127

Notice: Undefined property: Savegame::$items in E:\xampp\htdocs\FS19_Webstats\include\savegame\Prices.class.php on line 43

Warning: Invalid argument supplied for foreach() in E:\xampp\htdocs\FS19_Webstats\include\savegame\Prices.class.php on line 43

Mir ist aktuell unklar woher die Fehler kommen
- Fehlende Einstellung in der php.ini
- falsche PHP-Version
- Problem im Code
Vielleicht kannst du mir weiterhelfen. Danke

Hab es mit Felsbrunn und NF 2.1 probiert

**Comment by J0hnHawk** [comment]
Moin, 
das der Fehler nicht vernünftig abgefangen wird, liegt am Code und geht auf meine Kappe ;-) 
Es sieht für mich aber danach aus, als würde der Spielstand nicht (richtig) geladen/vorhanden sein.
Existiert die Datei "economy.xml" im Cache Verzeichnis? Spielst du lokal oder auf einem Server?

**Comment by ralfmuehle** [comment]
Hi,
es ist ein lokaler Spielstand und das Cache-Verzeichnis ist leer.

`<?xml version="1.0" encoding="UTF-8"?>
<config>
  <adminPass>....</adminPass>
  <map>felsbrunn</map>
  <savegame>
    <type>local</type>
    <path>C:\Users\....\Documents\My Games\FarmingSimulator2019\savegame3\</path>
  </savegame>
</config>`

**Comment by J0hnHawk** [comment]
Okay. Stimmt, bei lokalen Spielen bleibt das Cache Verzeichnis leer. in deinem Savegame-Ordner gibt es die Datei economy.xml aber?

**Comment by ralfmuehle** [comment]
ja die economy.xml ist vorhanden, habe ich auch schon testweise vom Savegame in das Cache-Verzeichnis kopiert, Fehlermeldungen kommen immer noch

**Comment by J0hnHawk** [comment]
Mit lokalen Spielständen habe ich die Web Stats schon ewig nicht mehr selbst getestet. Eigentlich ging ich davon aus, dass es mit denen am wenigsten Probleme gibt, da die Daten ja nicht noch erst herunter geladen werden müssen.
Ich schau mir das morgen mal genauer an. Im Moment habe ich keine Idee.

**Comment by J0hnHawk** [comment]
Der Fehler ist im letzten Commit behoben. ;-)

**Comment by ralfmuehle** [comment]
danke für das schnelle Beheben des Fehlers. Funktioniert super
