### ISSUE TITLE
FTP still nessesary?

### ISSUE THREAD

**Issue by J0hnHawk** [J0hnHawk/FS19_Webstats#45]
With the new possibility to download the complete savegame by login in the web interface the FTP functionality could be unnessesary.

However, because of the possibility to download only the realy needed files, FTP access could be a bit more performant. 

What do you think, keep the FTP functionality or drop it?

**Comment by TheGregorian** [comment]
Ich finde die Möglichkeit mit dem neuen Download auf jeden Fall angenehmer und nutze den FTP-Zugriff garnicht mehr

**Comment by ghost** [comment]
Hello, FTP download will come me slower :)
Login is great :)
Only in the log on the server at each request is:

[06 / Jul / 2019: 15: 38: 39] Login user 'fs19stats'
[06 / Jul / 2019: 15: 38: 41] Logout user 'fs19stats'
[06 / Jul / 2019: 15: 38: 41] Login user 'fs19stats'
Logged in and logged out again and then logged in again, is it OK?

I would suggest to edit cacheTimeout to 360 :)
5 minutes is enough to not unnecessarily download when the server has no change.

**Comment by J0hnHawk** [comment]
I found those "relogins" in our log too.  I'll commit a solution soon.

And I'll add an option for the $cacheTimeout value.

**Comment by J0hnHawk** [comment]
FTP will be gone in one of the next commits. Need to merge the setup rework branch after some testing.
