### ISSUE TITLE
Beste Verkauspreise - BGA nur bei Kauf berücksichtigen

### ISSUE THREAD

**Issue by TheGregorian** [J0hnHawk/FS19_Webstats#47]
Wir spielen auf Felsbrunn haben aber die BGA bisher nicht gekauft. Hier wäre die Frage ob man die BGA in der Übersicht "Beste Verkaufspreise" nur berücksichtigen könnte wenn sie wirklich im eigenen Besitz ist?

**Comment by J0hnHawk** [comment]
Das hat mich auch schon oft gestört. Hab ich mal mit eingebaut.
Ggf. muss ich die Lösung noch mal überarbeiten. Es gibt ja platzierbare Mods, die weitere Verkaufstrigger hinzufügen. Möglich, dass da auch nur die Farm verkaufen kann, die den Trigger gesetzt hat.
