### ISSUE TITLE
Map in Setup nicht auswählbar

### ISSUE THREAD

**Issue by TheGregorian** [J0hnHawk/FS19_Webstats#49]
gerade die neuste Version auf den Server gepackt. Bei der Einrichtung war es aber nicht möglich einen Map auszuwählen bzw. es stand garkeine Auswahlmöglichkeit zur Verfügung

**Comment by J0hnHawk** [comment]
Die Funktion "getMaps" in der functions.php ist noch nicht an den neuen Pfad angepasst :-/
Überall wo "./config" stehet muss "/maps" ergänzt werden. 
Bin gerade dabei den Setup-Dialog zu überarbeiten, da ist die Änderung dann mit drin.

**Comment by J0hnHawk** [comment]
Bis dahin:
[loadMap.txt](https://github.com/J0hnHawk/FS19_Webstats/files/3476953/loadMap.txt)
