### ISSUE TITLE
Bales on trailers are ignored

### ISSUE THREAD

**Issue by J0hnHawk** [J0hnHawk/FS19_Webstats#52]
Bales on trailers are ignored

**Comment by ghost** [comment]
Hi,
Are you planning to show the bales and pallet positions on the map?
Like in the FS17?

Thanks

**Comment by J0hnHawk** [comment]
Yes. Thats the reason why the map-images are still in the config dirs.

**Comment by J0hnHawk** [comment]
It seems, only bales are stored in the xml node of a trailer. Pallets do have their own nodes. So it is not possible to show pallets as loaded on trailer xy at the moment. 

I'm closing this issue. Bales are shown on trailers.
