### ISSUE TITLE
The unification of the same animals in the stable

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS19_Webstats#53]
Hi,
idea :)

We have the same stables in pigs and cows.
Wouldn't they be united in one stable?
We have:
**Big Cow husbandry (1 stables)**
Brahman brown

**Big Cow husbandry (2 stables)**
Cows (black & white)

Would be like this:
**Big cow husbandry**
Brahman brown
Cows (black & white)

Not so much category :)

![Výstřižek](https://user-images.githubusercontent.com/48215535/62926064-fa70c180-bdb3-11e9-96a5-bb52da9b8233.PNG)

thanks :)

**Comment by J0hnHawk** [comment]
Hm, how is it ingame? I never placed two same stables :-)
Problem could be the troughs. They might have different values in both stables.

**Comment by ghost** [comment]
One stables = one kind of animals :)
We have bought the same two for pigs and cows.

In the past, I solved it by adding mods and putting it into it
husbandryCowLarge.xml
husbandryCowLarge2.xml
to view statistics :)
But now I'm showing after update #46  both the same and so I do not need to insert mods :)
example:
![62926064-fa70c180-bdb3-11e9-96a5-bb52da9b8233](https://user-images.githubusercontent.com/48215535/62940740-81ce2d00-bdd4-11e9-8d53-6d7c1fa43601.PNG)

We do not want to have two kinds in one stable :)
I write just an idea or tip :) Not necessary :)

**Comment by ghost** [comment]
I solved and is no longer up to date :)
