### ISSUE TITLE
No image in new setup .)

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS19_Webstats#54]
In new setup - > dedicated
Pictures do not appear in Help
**Current address:**
/styles/fs19webstats/images/webuser.png
/styles/fs19webstats/images/webadress.png
/styles/fs19webstats/images/link_xml.png

**The correct address should be:**
/styles/fs19webstats/images/install/webuser.png
/styles/fs19webstats/images/install/webadress.png
/styles/fs19webstats/images/install/link_xml.png

thanks 👍

**Comment by J0hnHawk** [comment]
Should be in now ;-)
