### ISSUE TITLE
Images in PRICES are not displayed

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS19_Webstats#55]
Images UP and Down in PRICES are not displayed
priceDown.png
priceUp.png

thanks :)

**Comment by J0hnHawk** [comment]
Uhm, no, not a bug ;-) 
I'm using caret-up and down from Font awesome at the moment. I only copied both images above from ingame for later use - maybe.

Do you see these carets:
![grafik](https://user-images.githubusercontent.com/13779553/62970889-c972aa00-be10-11e9-939b-646702ac04c6.png)
?

**Comment by ghost** [comment]
Nothing really shows me :(
But version  0.8.0-10400 (13.08.2019) shows everything :(

![Výstřižek](https://user-images.githubusercontent.com/48215535/62974025-95e74e00-be17-11e9-84e3-a5e1cb69fd40.PNG)

**Comment by ghost** [comment]
commit 163fcd2fd6b13256f7da87fbda616c38418d07c9
include/savegame/Prices.class.php
when I undo changes, arrows appear :)

**Comment by J0hnHawk** [comment]
You were right. I had an old version on our webserver which still shows the carets. 
Now I moved the changes to the template.
