### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by MANFahrer-GF** [J0hnHawk/FS19_Webstats#6]
Hallo ,

 Wie geht denn die Installation bei mir wird immer ein Passwort verlangt?

**Comment by J0hnHawk** [comment]
Ich nehme an, du hast es alleine hinbekommen? Oder benötigst du noch Hilfe?

**Comment by MANFahrer-GF** [comment]
Ich habe es hinbekommen, jedoch bekomme ich Fehler nach der Installation

```
Warning: ftp_pwd(): Requested action not taken: internal server error in /var/www/vhosts/virtual-transport-group.de/httpdocs/vtg_forum/webls/include/install.php on line 164

Warning: ftp_chdir(): Syntax error: CWD requires an argument. in /var/www/vhosts/virtual-transport-group.de/httpdocs/vtg_forum/webls/include/install.php on line 168
```
`Als Ordner wurde: /profile/savegame4/ eingegeben

GPortal FTP Server: Ja`

hier ist der Link zum WebStat: https://virtual-transport-group.de/webls

**Comment by J0hnHawk** [comment]
Diese dusseligen G-Portal Server :-/ Selbst einfachste FTP Befehle werden abgeblockt.
Letztlich sind die beiden Befehle, die zu der Warnung führen aber unkritisch. Ich habe die jetzt auskommentiert. 
Die Installation lief bei dir dann ja trotzdem durch. Allerdings sehe ich diverse weitere Fehler, die bei dir angezeigt werden. Ein paar konnte ich dank deines Links schon ausmerzen. 
Magst du mir vielleicht euren Spielstand vom Server zukommen lassen? Da tauchen ein paar Konstellationen auf, die ich offensichtlich bisher noch nicht berücksichtigt habe.

**Comment by MANFahrer-GF** [comment]
Guten Morgen, 

hier der aktuelle Spielstand von heute 8 Uhr 

[savegame4_backup2019-02-04_08-00.zip](https://github.com/J0hnHawk/FS19_Webstats/files/2826884/savegame4_backup2019-02-04_08-00.zip)

**Comment by J0hnHawk** [comment]
Moin. Danke!
Ich schließe dieses Thema mal. Aus den Fehlermeldungen mit deinem Spielstand mach ich neue Themen auf.

**Comment by MANFahrer-GF** [comment]
nach deiner Änderung habe ich alles gelöscht und neu hochgeladen und jetzt bekomme ich keine Verbindung mehr, nach der Neuinstallation per FTP.

`Fehler! ##ERROR_FTPPATH##`

**Comment by J0hnHawk** [comment]
Mmpf. :-/
Ich habe das Überprüfen des Verzeichnisses noch mal geändert (Zeilen 164 und 168 in der install.php) Probiere mal ob es so funktioniert. 
Wenn nicht, kannst du mit dem Löschen der beiden @-Zeichen den Stand von gestern wiederherstellen - dann kommen auch wieder die 2 Warnmeldungen. Aber vielleicht/hoffentlich funktioniert es mit dem @-Zeichen.

**Comment by MANFahrer-GF** [comment]
Hallo, 

danke für die Anpassung ist jetzt OK (ohne Fehler) bei GPortal Server.
