### ISSUE TITLE
Any hints on creating a custom map config file?

### ISSUE THREAD

**Issue by rupertd** [J0hnHawk/FS19_Webstats#63]
Hi there,

Thanks for this stats tool, very nice indeed.  I run a multiplayer server on a custom map. The map has 48 or so 'farmlands' and many other 'purchasable' land plots.  I have been crawling through the underlying map data, tried using the giants editor, crawled through reams of XML files but I cannot find the inputs required to create the custom map farmlands.xml required by your Webstats engine.

Do you have any hints or tips as to which files to look in, which tools to use?  You have X and Z coordinates for each field.  What do they mean?  Where do you get those coords from?  What if the fields are not square; how do those coords work? Are they just the centrepoint of each plot for some use later on with a map etc?

The key question is; 

How do I accurately obtain the FARMLAND ID's and PURCHASABLE LAND ID's such that all land holdings of players are correctly shown in the balance sheet?  You obviously have a technique that works to dig this info out of a map, so can you please describe your method so I can follow it with our custom map?

Many thanks!

**Comment by rupertd** [comment]
Don't worry, I sorted it out myself.

**Comment by CurtisFeatures** [comment]
@rupertd 

please could you tell me how you got your farmlands xml?
